server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:                 
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: library-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: library
          __path__: /var/log/library.log

    pipeline_stages:
      - json:
          expressions:
            level: level
            operation: operation
            component: component
      - labels:
          level:
          operation:
          component:
